server:
  type: simple
  applicationContextPath: /
  adminContextPath: /admin
logging:
  level: INFO
  loggers:
    spoken: DEBUG
    org.eclipse.jetty: WARN
  console:
    logFormat: "%-5level thread=%thread %logger: %m%n%xEx"
